# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file-client.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66ile-client.proto\x12\nfileclient\"E\n\x10\x46ileRulesRequest\x12\x0e\n\x06userID\x18\x01 \x01(\t\x12\r\n\x05orgID\x18\x02 \x01(\t\x12\x12\n\nserviceCtx\x18\x03 \x01(\t\"n\n\x11\x46ileRulesResponse\x12\r\n\x05s3Dir\x18\x01 \x01(\t\x12\x13\n\x0bmaxFileSize\x18\x02 \x01(\x03\x12\x18\n\x10\x61llowedFileTypes\x18\x03 \x03(\t\x12\x1b\n\x13\x61llowedContentTypes\x18\x04 \x03(\t\"y\n\x08\x46ileInfo\x12\x18\n\x10originalFileName\x18\x01 \x01(\t\x12\x10\n\x08\x66ileName\x18\x02 \x01(\t\x12\r\n\x05s3Key\x18\x03 \x01(\t\x12\x13\n\x0b\x63ontentType\x18\x04 \x01(\t\x12\x0c\n\x04size\x18\x05 \x01(\x03\x12\x0f\n\x07\x66ormKey\x18\x06 \x01(\t\"\x9e\x01\n\x13\x46ileSaveDataRequest\x12\x0e\n\x06userID\x18\x01 \x01(\t\x12\r\n\x05orgID\x18\x02 \x01(\t\x12\x12\n\nserviceCtx\x18\x04 \x01(\t\x12\n\n\x02ip\x18\x05 \x01(\t\x12\x0f\n\x07\x62\x61tchID\x18\x06 \x01(\t\x12\x0e\n\x06\x66ormID\x18\x07 \x01(\t\x12\'\n\tfileInfos\x18\x08 \x03(\x0b\x32\x14.fileclient.FileInfo\"&\n\x14\x46ileSaveDataResponse\x12\x0e\n\x06output\x18\x01 \x01(\x0c\x32\xac\x01\n\nFileClient\x12K\n\x0cGetFileRules\x12\x1c.fileclient.FileRulesRequest\x1a\x1d.fileclient.FileRulesResponse\x12Q\n\x0cSaveFileData\x12\x1f.fileclient.FileSaveDataRequest\x1a .fileclient.FileSaveDataResponseB#Z!github.com/moly-space/molylibs/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z!github.com/moly-space/molylibs/pb'
  _globals['_FILERULESREQUEST']._serialized_start=33
  _globals['_FILERULESREQUEST']._serialized_end=102
  _globals['_FILERULESRESPONSE']._serialized_start=104
  _globals['_FILERULESRESPONSE']._serialized_end=214
  _globals['_FILEINFO']._serialized_start=216
  _globals['_FILEINFO']._serialized_end=337
  _globals['_FILESAVEDATAREQUEST']._serialized_start=340
  _globals['_FILESAVEDATAREQUEST']._serialized_end=498
  _globals['_FILESAVEDATARESPONSE']._serialized_start=500
  _globals['_FILESAVEDATARESPONSE']._serialized_end=538
  _globals['_FILECLIENT']._serialized_start=541
  _globals['_FILECLIENT']._serialized_end=713
# @@protoc_insertion_point(module_scope)
