# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message-service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15message-service.proto\x12\x0emessageservice\"\x8f\x01\n\x0eMessageRequest\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x0c\n\x04\x66rom\x18\x03 \x01(\t\x12\n\n\x02to\x18\x04 \x01(\t\x12\x30\n\x0bmessageType\x18\x05 \x01(\x0e\x32\x1b.messageservice.MessageType\x12\x0f\n\x07message\x18\x06 \x01(\x0c\"4\n\x0fProgressMessage\x12\x0f\n\x07\x63ontext\x18\x01 \x01(\t\x12\x10\n\x08progress\x18\x02 \x01(\x05\"\xcc\x01\n\x16ProgressMessageRequest\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\n\n\x02to\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t\x12\x13\n\x0bprogressCtx\x18\x05 \x01(\t\x12\x30\n\x07\x63ommand\x18\x06 \x01(\x0e\x32\x1f.messageservice.ProgressCommand\x12\x31\n\x08progress\x18\x07 \x01(\x0b\x32\x1f.messageservice.ProgressMessage\"\"\n\x0fMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08*9\n\x0bMessageType\x12\r\n\tNONE_TYPE\x10\x00\x12\x08\n\x04TEXT\x10\x01\x12\x08\n\x04JSON\x10\x02\x12\x07\n\x03XML\x10\x03*B\n\x0fProgressCommand\x12\x10\n\x0cNONE_COMMAND\x10\x00\x12\x07\n\x03\x41\x44\x44\x10\x01\x12\n\n\x06UPDATE\x10\x02\x12\x08\n\x04\x44ONE\x10\x03\x32\x87\x02\n\x0eMessageService\x12N\n\x0bSendMessage\x12\x1e.messageservice.MessageRequest\x1a\x1f.messageservice.MessageResponse\x12L\n\tBroadcast\x12\x1e.messageservice.MessageRequest\x1a\x1f.messageservice.MessageResponse\x12W\n\x0cSendProgress\x12&.messageservice.ProgressMessageRequest\x1a\x1f.messageservice.MessageResponseB#Z!github.com/moly-space/molylibs/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z!github.com/moly-space/molylibs/pb'
  _globals['_MESSAGETYPE']._serialized_start=484
  _globals['_MESSAGETYPE']._serialized_end=541
  _globals['_PROGRESSCOMMAND']._serialized_start=543
  _globals['_PROGRESSCOMMAND']._serialized_end=609
  _globals['_MESSAGEREQUEST']._serialized_start=42
  _globals['_MESSAGEREQUEST']._serialized_end=185
  _globals['_PROGRESSMESSAGE']._serialized_start=187
  _globals['_PROGRESSMESSAGE']._serialized_end=239
  _globals['_PROGRESSMESSAGEREQUEST']._serialized_start=242
  _globals['_PROGRESSMESSAGEREQUEST']._serialized_end=446
  _globals['_MESSAGERESPONSE']._serialized_start=448
  _globals['_MESSAGERESPONSE']._serialized_end=482
  _globals['_MESSAGESERVICE']._serialized_start=612
  _globals['_MESSAGESERVICE']._serialized_end=875
# @@protoc_insertion_point(module_scope)
