# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tree-service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12tree-service.proto\x12\x0btreeservice\"G\n\x0bTreeRequest\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\r\n\x05orgID\x18\x03 \x01(\t\x12\r\n\x05order\x18\x04 \x01(\t\x12\x0c\n\x04slug\x18\x05 \x01(\t\"\x1c\n\x0cTreeResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1c\n\x0c\x42oolResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x08\x32\x9d\x06\n\x0bTreeService\x12\x43\n\x0cGetAncestors\x12\x18.treeservice.TreeRequest\x1a\x19.treeservice.TreeResponse\x12>\n\x07GetRoot\x12\x18.treeservice.TreeRequest\x1a\x19.treeservice.TreeResponse\x12>\n\x07GetTree\x12\x18.treeservice.TreeRequest\x1a\x19.treeservice.TreeResponse\x12\x45\n\x0eGetTreeAsArray\x12\x18.treeservice.TreeRequest\x1a\x19.treeservice.TreeResponse\x12=\n\x06GetOne\x12\x18.treeservice.TreeRequest\x1a\x19.treeservice.TreeResponse\x12=\n\x06\x44\x65lete\x12\x18.treeservice.TreeRequest\x1a\x19.treeservice.TreeResponse\x12=\n\x06Update\x12\x18.treeservice.TreeRequest\x1a\x19.treeservice.TreeResponse\x12\x41\n\nGetSibling\x12\x18.treeservice.TreeRequest\x1a\x19.treeservice.TreeResponse\x12\x42\n\x0bGetChildren\x12\x18.treeservice.TreeRequest\x1a\x19.treeservice.TreeResponse\x12>\n\x07GetPath\x12\x18.treeservice.TreeRequest\x1a\x19.treeservice.TreeResponse\x12@\n\tGetParent\x12\x18.treeservice.TreeRequest\x1a\x19.treeservice.TreeResponse\x12<\n\x05IsEnd\x12\x18.treeservice.TreeRequest\x1a\x19.treeservice.BoolResponseB#Z!github.com/moly-space/molylibs/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tree_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z!github.com/moly-space/molylibs/pb'
  _globals['_TREEREQUEST']._serialized_start=35
  _globals['_TREEREQUEST']._serialized_end=106
  _globals['_TREERESPONSE']._serialized_start=108
  _globals['_TREERESPONSE']._serialized_end=136
  _globals['_BOOLRESPONSE']._serialized_start=138
  _globals['_BOOLRESPONSE']._serialized_end=166
  _globals['_TREESERVICE']._serialized_start=169
  _globals['_TREESERVICE']._serialized_end=966
# @@protoc_insertion_point(module_scope)
