/*
 Navicat Premium Data Transfer

 Source Server         : Docker moly mongo
 Source Server Type    : MongoDB
 Source Server Version : 70008 (7.0.8)
 Source Host           : localhost:27017
 Source Schema         : rbac

 Target Server Type    : MongoDB
 Target Server Version : 70008 (7.0.8)
 File Encoding         : 65001

 Date: 28/07/2024 18:40:25
*/

// ----------------------------
// Collection structure for models
// ----------------------------
db.getCollection('models').drop()
db.createCollection('models')

// ----------------------------
// Documents of models
// ----------------------------
db.getCollection('models').insert([
  {
    _id: ObjectId('644fb7ebcb7c89d64e01ff42'),
    service: 'broker',
    model:
      '[request_definition]\nr = sub, obj, act\n\n[policy_definition]\np = sub, obj, act\n\n[role_definition]\ng = _, _\n\n[policy_effect]\ne = some(where (p.eft == allow))\n\n[matchers]\nm = (r.sub == p.sub || g(r.sub, p.sub)) && keyMatch(r.obj, p.obj) && (r.act == p.act || p.act == "*")',
    host: '',
  },
  {
    _id: ObjectId('652d9bd3778fa4bd5b014906'),
    service: 'organization',
    model:
      '[request_definition]\nr = sub, obj, act\n\n[policy_definition]\np = sub, obj, act\n\n[role_definition]\ng = _, _\n\n[policy_effect]\ne = some(where (p.eft == allow))\n\n[matchers]\nm = (r.sub == p.sub || g(r.sub, p.sub)) && keyMatch(r.obj, p.obj) && (r.act == p.act || p.act == "*")',
    host: 'localhost',
  },
  {
    _id: ObjectId('662be0599ae32e83c80f7739'),
    service: 'rbac',
    model:
      '[request_definition]\nr = sub, obj, act\n\n[policy_definition]\np = sub, obj, act\n\n[role_definition]\ng = _, _\n\n[policy_effect]\ne = some(where (p.eft == allow))\n\n[matchers]\nm = (r.sub == p.sub || g(r.sub, p.sub)) && keyMatch(r.obj, p.obj) && (r.act == p.act || p.act == "*")',
    host: 'localhost',
  },
  {
    _id: ObjectId('6648ebeb6829f565220d5998'),
    service: 'organization',
    model:
      '[request_definition]\nr = sub, obj, act\n\n[policy_definition]\np = sub, obj, act\n\n[role_definition]\ng = _, _\n\n[policy_effect]\ne = some(where (p.eft == allow))\n\n[matchers]\nm = (r.sub == p.sub || g(r.sub, p.sub)) && keyMatch(r.obj, p.obj) && (r.act == p.act || p.act == "fuckstar")',
    host: 'localhost',
    ctx: 'formEditView',
  },
])

// ----------------------------
// Collection structure for policies
// ----------------------------
db.getCollection('policies').drop()
db.createCollection('policies')

// ----------------------------
// Documents of policies
// ----------------------------
db.getCollection('policies').insert([
  {
    _id: ObjectId('6536dfa9778fa4bd5b01490d'),
    service: 'broker',
    type: 'p',
    sub: 'admin',
    obj: '/test',
    act: '*',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('6536dfa9778fa4bd5b01490e'),
    service: 'broker',
    type: 'p',
    sub: 'member',
    obj: '/test',
    act: '*',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('6536dfa9778fa4bd5b01490f'),
    service: 'broker',
    type: 'p',
    sub: 'admin',
    obj: '/admin',
    act: '*',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('6536dfa9778fa4bd5b014910'),
    service: 'broker',
    type: 'p',
    sub: 'guest',
    obj: '/user/save',
    act: 'POST',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('6536dfa9778fa4bd5b014911'),
    service: 'broker',
    type: 'p',
    sub: 'guest',
    obj: '/user/login',
    act: 'POST',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('6536dfa9778fa4bd5b014912'),
    service: 'broker',
    type: 'p',
    sub: 'guest',
    obj: '/user/user',
    act: 'GET',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('6536dfa9778fa4bd5b014913'),
    service: 'broker',
    type: 'p',
    sub: 'guest',
    obj: '/user/refreshtoken',
    act: 'GET',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('6536dfa9778fa4bd5b014914'),
    service: 'broker',
    type: 'p',
    sub: 'guest',
    obj: '/user/logout',
    act: 'POST',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('6536dfa9778fa4bd5b014915'),
    service: 'broker',
    type: 'p',
    sub: 'guest',
    obj: '/sandbox/*',
    act: '*',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('6536dfa9778fa4bd5b014916'),
    service: 'broker',
    type: 'p',
    sub: 'guest',
    obj: '/list',
    act: 'GET',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('6536dfa9778fa4bd5b014917'),
    service: 'broker',
    type: 'g',
    sub: 'member',
    obj: 'guest',
    act: null,
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('6536dfa9778fa4bd5b014918'),
    service: 'broker',
    type: 'g',
    sub: 'admin',
    obj: 'member',
    act: null,
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('6536dfa9778fa4bd5b014919'),
    service: 'broker',
    type: 'p',
    sub: 'guest',
    obj: '/user/verifyemail',
    act: 'POST',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('6536dfa9778fa4bd5b01491a'),
    service: 'broker',
    type: 'p',
    sub: 'guest',
    obj: '/organization/settings',
    act: 'GET',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('6536dfa9778fa4bd5b01491b'),
    service: 'organization',
    type: 'p',
    sub: 'member',
    obj: '653d183801c9db2b560390d2',
    act: 'topMenu',
    host: 'localhost',
    unit: 'menu',
    ctx: 'menu',
  },
  {
    _id: ObjectId('6536dfa9778fa4bd5b01491c'),
    service: 'organization',
    sub: 'member',
    type: 'p',
    obj: '653d19da01c9db2b560390d3',
    act: 'topMenu',
    host: 'localhost',
    unit: 'menu',
    ctx: 'menu',
  },
  {
    _id: ObjectId('6536dfa9778fa4bd5b01491d'),
    service: 'organization',
    sub: 'member',
    type: 'p',
    obj: '653d19f701c9db2b560390d4',
    act: 'topMenu',
    host: 'localhost',
    unit: 'menu',
    ctx: 'menu',
  },
  {
    _id: ObjectId('6536dfa9778fa4bd5b01491e'),
    service: 'organization',
    host: 'localhost',
    sub: 'admin',
    obj: 'member',
    type: 'g',
    unit: 'menu',
    act: null,
    ctx: 'menu',
  },
  {
    _id: ObjectId('654950bdeddcc2bcb70fc292'),
    service: 'broker',
    type: 'p',
    sub: 'member',
    obj: '/organization/items',
    act: 'GET',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('658f24bded3564c9b3004d62'),
    service: 'broker',
    type: 'p',
    sub: 'member',
    obj: '/user/settings',
    act: 'PUT',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('65d0d90c4becb142e2024880'),
    obj: '/user/password',
    act: 'PUT',
    sub: 'member',
    type: 'p',
    service: 'broker',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('65d0d9134becb142e2024881'),
    obj: '/user/account',
    act: 'PUT',
    sub: 'member',
    type: 'p',
    service: 'broker',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('65e080e2e7122d564603f433'),
    service: 'broker',
    type: 'p',
    sub: 'guest',
    obj: '/sandbox/sandbox',
    act: 'GET',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('65f1f5edadf2cf52220c9092'),
    service: 'broker',
    type: 'p',
    sub: 'member',
    obj: '/user/password',
    act: 'POST',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('660331d2ec327629410f0833'),
    service: 'broker',
    type: 'p',
    sub: 'member',
    obj: '/user/email',
    act: 'POST',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('66043737ec327629410f0837'),
    service: 'broker',
    type: 'p',
    sub: 'guest',
    obj: '/auth/forgotpassword',
    act: 'POST',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('6604374cec327629410f0838'),
    service: 'broker',
    type: 'p',
    sub: 'guest',
    obj: '/auth/password',
    act: 'PUT',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('6604d22dec327629410f083a'),
    service: 'broker',
    type: 'p',
    sub: 'guest',
    obj: '/files',
    act: 'POST',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('661cf80540b3262f00007276'),
    service: 'organization',
    type: 'p',
    sub: 'admin',
    obj: '661cf75340b3262f00007275',
    act: 'adminLeftNavMenu',
    host: 'localhost',
    unit: 'menu',
    ctx: 'menu',
  },
  {
    _id: ObjectId('661cf80a40b3262f00007277'),
    service: 'organization',
    type: 'p',
    sub: 'admin',
    obj: '661cf72240b3262f00007274',
    act: 'adminLeftNavMenu',
    host: 'localhost',
    unit: 'menu',
    ctx: 'menu',
  },
  {
    _id: ObjectId('661d279940b3262f0000727a'),
    service: 'organization',
    type: 'p',
    sub: 'member',
    obj: '661d26a940b3262f00007278',
    act: 'userDropdownMenu',
    host: 'localhost',
    unit: 'menu',
    ctx: 'menu',
  },
  {
    _id: ObjectId('661d27ba40b3262f0000727b'),
    service: 'organization',
    type: 'p',
    sub: 'admin',
    obj: '661d273c40b3262f00007279',
    act: 'userDropdownMenu',
    host: 'localhost',
    unit: 'menu',
    ctx: 'menu',
  },
  {
    _id: ObjectId('661dca0cefbc811f750274c5'),
    service: 'organization',
    type: 'p',
    sub: 'member',
    obj: '661dc5e7efbc811f750274c1',
    act: 'userLeftNavMenu',
    host: 'localhost',
    unit: 'menu',
    ctx: 'menu',
  },
  {
    _id: ObjectId('661dca0eefbc811f750274c6'),
    service: 'organization',
    type: 'p',
    sub: 'member',
    obj: '661dc66eefbc811f750274c2',
    act: 'userLeftNavMenu',
    host: 'localhost',
    unit: 'menu',
    ctx: 'menu',
  },
  {
    _id: ObjectId('661dca0fefbc811f750274c7'),
    service: 'organization',
    type: 'p',
    sub: 'member',
    obj: '661dc6bcefbc811f750274c3',
    act: 'userLeftNavMenu',
    host: 'localhost',
    unit: 'menu',
    ctx: 'menu',
  },
  {
    _id: ObjectId('661dca0fefbc811f750274c8'),
    service: 'organization',
    type: 'p',
    sub: 'member',
    obj: '661dc6f1efbc811f750274c4',
    act: 'userLeftNavMenu',
    host: 'localhost',
    unit: 'menu',
    ctx: 'menu',
  },
  {
    _id: ObjectId('6622d1ed9ae32e83c80f7732'),
    service: 'organization',
    type: 'p',
    sub: 'member',
    act: 'userMetadata',
    host: 'localhost',
    unit: 'form',
    obj: '',
    ctx: 'form',
  },
  {
    _id: ObjectId('6622d20c9ae32e83c80f7733'),
    service: 'organization',
    type: 'p',
    sub: 'member',
    act: 'testForm',
    host: 'localhost',
    unit: 'form',
    obj: '',
    ctx: 'form',
  },
  {
    _id: ObjectId('662968219ae32e83c80f7734'),
    service: 'organization',
    type: 'p',
    sub: 'admin',
    act: 'adminOrganizationInformation',
    host: 'localhost',
    unit: 'form',
    obj: '',
    ctx: 'form',
  },
  {
    _id: ObjectId('662bdadf9ae32e83c80f7735'),
    service: 'rbac',
    type: 'p',
    sub: 'member',
    host: 'localhost',
    act: '_',
    unit: 'filter',
    ctx: 'filter',
  },
  {
    _id: ObjectId('662bdaf09ae32e83c80f7736'),
    service: 'rbac',
    type: 'p',
    sub: 'member',
    host: 'localhost',
    act: '__',
    unit: 'filter',
    ctx: 'filter',
  },
  {
    _id: ObjectId('662bdb069ae32e83c80f7737'),
    service: 'rbac',
    type: 'p',
    sub: 'admin',
    host: 'localhost',
    act: '__',
    unit: 'filter',
    ctx: 'filter',
  },
  {
    _id: ObjectId('662bdb139ae32e83c80f7738'),
    sub: 'super',
    service: 'rbac',
    type: 'p',
    host: 'localhost',
    act: '',
    unit: 'filter',
    ctx: 'filter',
  },
  {
    _id: ObjectId('662c3ce34d14cabf2e0bf321'),
    service: 'broker',
    type: 'p',
    sub: 'admin',
    obj: '/organization/info',
    act: 'PUT',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('662c3d084d14cabf2e0bf322'),
    service: 'broker',
    type: 'p',
    sub: 'admin',
    obj: '/organization/info',
    act: 'GET',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('662d342b4d14cabf2e0bf328'),
    service: 'broker',
    type: 'p',
    sub: 'admin',
    obj: '/admin/users',
    act: 'GET',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('662d6caa4d14cabf2e0bf329'),
    obj: 'admin',
    service: 'broker',
    sub: 'super',
    type: 'g',
    act: null,
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('662d6d114d14cabf2e0bf32a'),
    service: 'organization',
    type: 'g',
    sub: 'super',
    obj: 'admin',
    act: null,
    host: 'localhost',
    unit: 'menu',
    ctx: 'menu',
  },
  {
    _id: ObjectId('662ff64c4d14cabf2e0bf32b'),
    obj: '/admin/user',
    service: 'broker',
    type: 'p',
    sub: 'admin',
    act: 'PUT',
    host: '',
    unit: null,
  },
  {
    _id: ObjectId('662ff6654d14cabf2e0bf32c'),
    service: 'broker',
    type: 'p',
    sub: 'admin',
    obj: '/admin/user',
    act: 'POST',
    host: '',
  },
  {
    _id: ObjectId('66320df74d14cabf2e0bf32f'),
    service: 'broker',
    type: 'p',
    sub: 'admin',
    obj: '/admin/user',
    act: 'DELETE',
    host: '',
  },
  {
    _id: ObjectId('66320ef04d14cabf2e0bf330'),
    service: 'broker',
    type: 'p',
    sub: 'admin',
    obj: '/admin/organization/form-order',
    act: 'PUT',
    host: '',
  },
  {
    _id: ObjectId('66320f074d14cabf2e0bf331'),
    service: 'broker',
    type: 'p',
    sub: 'admin',
    obj: '/admin/organization/form',
    act: 'DELETE',
    host: '',
  },
  {
    _id: ObjectId('66320f1c4d14cabf2e0bf332'),
    service: 'broker',
    type: 'p',
    sub: 'admin',
    obj: '/admin/organization/form',
    act: 'PUT',
    host: '',
  },
  {
    _id: ObjectId('66320f424d14cabf2e0bf333'),
    service: 'broker',
    type: 'p',
    sub: 'admin',
    obj: '/admin/organization/form',
    act: 'PATCH',
    host: '',
  },
  {
    _id: ObjectId('6633da564d14cabf2e0bf33a'),
    act: 'POST',
    host: '',
    obj: '/admin/organization/form',
    service: 'broker',
    sub: 'admin',
    type: 'p',
    unit: '',
  },
  {
    _id: ObjectId('663bc7504d14cabf2e0bf33d'),
    service: 'broker',
    type: 'p',
    sub: 'admin',
    obj: '/admin/organization/form',
    act: 'GET',
    host: '',
    unit: '',
  },
  {
    _id: ObjectId('6646503d6829f565220d5993'),
    service: 'organization',
    type: 'p',
    sub: 'member',
    act: 'member',
    host: 'localhost',
    unit: 'role',
    obj: '1',
    ctx: 'role',
  },
  {
    _id: ObjectId('664650626829f565220d5994'),
    service: 'organization',
    type: 'p',
    sub: 'super',
    act: 'super',
    host: 'localhost',
    unit: 'role',
    obj: 3,
    ctx: 'role',
  },
  {
    _id: ObjectId('66465f616829f565220d5995'),
    service: 'organization',
    type: 'p',
    sub: 'admin',
    act: 'admin',
    obj: '2',
    host: 'localhost',
    unit: 'role',
    ctx: 'role',
  },
  {
    _id: ObjectId('664660186829f565220d5996'),
    service: 'rbac',
    type: 'g',
    sub: 'admin',
    obj: 'member',
  },
  {
    _id: ObjectId('664660266829f565220d5997'),
    type: 'g',
    sub: 'super',
    obj: 'admin',
    service: 'rbac',
  },
  {
    _id: ObjectId('664907496829f565220d599a'),
    ctx: 'formEditView',
    obj: 'member',
    service: 'organization',
    sub: 'admin',
    type: 'g',
    host: 'localhost',
  },
  {
    _id: ObjectId('6649077c6829f565220d599b'),
    service: 'organization',
    type: 'g',
    sub: 'super',
    obj: 'admin',
    host: 'localhost',
    ctx: 'formEditView',
  },
  {
    _id: ObjectId('6649e8f76829f565220d599c'),
    obj: 'member',
    service: 'organization',
    sub: 'admin',
    type: 'g',
    ctx: 'form',
    host: 'localhost',
    unit: 'form',
  },
  {
    _id: ObjectId('6649e9356829f565220d599d'),
    service: 'organization',
    type: 'g',
    sub: 'super',
    obj: 'admin',
    host: 'localhost',
    unit: 'form',
    ctx: 'form',
  },
  {
    _id: ObjectId('6649eb446829f565220d599e'),
    service: 'organization',
    type: 'g',
    sub: 'admin',
    obj: 'member',
    host: 'localhost',
    ctx: 'role',
  },
  {
    _id: ObjectId('6649eb576829f565220d599f'),
    service: 'organization',
    type: 'g',
    sub: 'super',
    obj: 'admin',
    host: 'localhost',
    unit: 'role',
    ctx: 'role',
  },
  {
    _id: ObjectId('664c8b216829f565220d59a1'),
    service: 'broker',
    type: 'p',
    sub: 'guest',
    obj: '/user/setpassword',
    act: 'POST',
  },
  {
    _id: ObjectId('66545a876829f565220d59a6'),
    service: 'broker',
    type: 'p',
    sub: 'member',
    obj: '/user/store',
    act: 'POST',
  },
  {
    _id: ObjectId('66545a996829f565220d59a7'),
    service: 'broker',
    type: 'p',
    sub: 'member',
    obj: '/user/store',
    act: 'GET',
  },
  {
    _id: ObjectId('66545aa16829f565220d59a8'),
    service: 'broker',
    type: 'p',
    sub: 'member',
    obj: '/user/store',
    act: 'DELETE',
  },
  {
    _id: ObjectId('66545aa56829f565220d59a9'),
    service: 'broker',
    type: 'p',
    sub: 'member',
    obj: '/user/store',
    act: 'PUT',
  },
  {
    _id: ObjectId('66843c2bd81a728793025394'),
    service: 'broker',
    type: 'p',
    sub: 'guest',
    obj: '/tree',
    act: 'GET',
    host: '',
  },
  {
    _id: ObjectId('66843d18d81a728793025395'),
    service: 'broker',
    type: 'p',
    sub: 'admin',
    obj: '/admin/tree',
    act: 'GET',
  },
  {
    _id: ObjectId('66843d28d81a728793025396'),
    service: 'broker',
    type: 'p',
    sub: 'admin',
    obj: '/admin/tree',
    act: 'POST',
  },
  {
    _id: ObjectId('66843d3cd81a728793025397'),
    service: 'broker',
    type: 'p',
    sub: 'admin',
    obj: '/admin/tree',
    act: 'PUT',
  },
  {
    _id: ObjectId('66843d4cd81a728793025398'),
    service: 'broker',
    type: 'p',
    sub: 'admin',
    obj: '/admin/tree',
    act: 'DELETE',
  },
  {
    _id: ObjectId('66844043d81a72879302539f'),
    service: 'organization',
    type: 'p',
    sub: 'admin',
    obj: '66843fc3d81a72879302539e',
    act: 'adminLeftNavMenu',
    ctx: 'menu',
    host: 'localhost',
    unit: 'menu',
  },
  {
    _id: ObjectId('66870529d81a7287930253a0'),
    service: 'broker',
    type: 'p',
    sub: 'admin',
    obj: '/admin/trees',
    act: 'GET',
    host: '',
  },
  {
    _id: ObjectId('668d8f6ad81a7287930253a3'),
    service: 'broker',
    type: 'p',
    sub: 'admin',
    obj: '/admin/tree/reorder',
    act: 'PUT',
  },
  {
    _id: ObjectId('6696e38cd81a7287930253a5'),
    service: 'broker',
    type: 'p',
    sub: 'admin',
    obj: '/admin/trees',
    act: 'POST',
  },
])
