version: '3'

services:
  sftp:
    image: atmoz/sftp
    container_name: sftp_server
    ports:
      - "2222:22"
    volumes:
      - ./sftp_data:/home/user/upload
    environment:
      - SFTP_USERS=user:password:1000
    restart: always 