//protoc -Ipb --go_out=./pb --go_opt=module=github.com/moly-space/molylibs/pb --go-grpc_out=./pb --go-grpc_opt=module=github.com/moly-space/molylibs/pb pb/file-client.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: file-client.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileRulesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID     string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	OrgID      string `protobuf:"bytes,2,opt,name=orgID,proto3" json:"orgID,omitempty"`
	ServiceCtx string `protobuf:"bytes,3,opt,name=serviceCtx,proto3" json:"serviceCtx,omitempty"`
}

func (x *FileRulesRequest) Reset() {
	*x = FileRulesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRulesRequest) ProtoMessage() {}

func (x *FileRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRulesRequest.ProtoReflect.Descriptor instead.
func (*FileRulesRequest) Descriptor() ([]byte, []int) {
	return file_file_client_proto_rawDescGZIP(), []int{0}
}

func (x *FileRulesRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *FileRulesRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *FileRulesRequest) GetServiceCtx() string {
	if x != nil {
		return x.ServiceCtx
	}
	return ""
}

type FileRulesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S3Dir               string   `protobuf:"bytes,1,opt,name=s3Dir,proto3" json:"s3Dir,omitempty"`
	MaxFileSize         int64    `protobuf:"varint,2,opt,name=maxFileSize,proto3" json:"maxFileSize,omitempty"`
	AllowedFileTypes    []string `protobuf:"bytes,3,rep,name=allowedFileTypes,proto3" json:"allowedFileTypes,omitempty"`       //video, audio, imageg etc..
	AllowedContentTypes []string `protobuf:"bytes,4,rep,name=allowedContentTypes,proto3" json:"allowedContentTypes,omitempty"` //image/jpeg, video/mp4 etc..
}

func (x *FileRulesResponse) Reset() {
	*x = FileRulesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRulesResponse) ProtoMessage() {}

func (x *FileRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRulesResponse.ProtoReflect.Descriptor instead.
func (*FileRulesResponse) Descriptor() ([]byte, []int) {
	return file_file_client_proto_rawDescGZIP(), []int{1}
}

func (x *FileRulesResponse) GetS3Dir() string {
	if x != nil {
		return x.S3Dir
	}
	return ""
}

func (x *FileRulesResponse) GetMaxFileSize() int64 {
	if x != nil {
		return x.MaxFileSize
	}
	return 0
}

func (x *FileRulesResponse) GetAllowedFileTypes() []string {
	if x != nil {
		return x.AllowedFileTypes
	}
	return nil
}

func (x *FileRulesResponse) GetAllowedContentTypes() []string {
	if x != nil {
		return x.AllowedContentTypes
	}
	return nil
}

type FileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginalFileName string `protobuf:"bytes,1,opt,name=originalFileName,proto3" json:"originalFileName,omitempty"`
	FileName         string `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	S3Key            string `protobuf:"bytes,3,opt,name=s3Key,proto3" json:"s3Key,omitempty"`
	ContentType      string `protobuf:"bytes,4,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Size             int64  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	FormKey          string `protobuf:"bytes,6,opt,name=formKey,proto3" json:"formKey,omitempty"`
	UuID             string `protobuf:"bytes,7,opt,name=uuID,proto3" json:"uuID,omitempty"`
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_file_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_file_client_proto_rawDescGZIP(), []int{2}
}

func (x *FileInfo) GetOriginalFileName() string {
	if x != nil {
		return x.OriginalFileName
	}
	return ""
}

func (x *FileInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileInfo) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *FileInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetFormKey() string {
	if x != nil {
		return x.FormKey
	}
	return ""
}

func (x *FileInfo) GetUuID() string {
	if x != nil {
		return x.UuID
	}
	return ""
}

type FileSaveDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID     string      `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	OrgID      string      `protobuf:"bytes,2,opt,name=orgID,proto3" json:"orgID,omitempty"`
	ServiceCtx string      `protobuf:"bytes,4,opt,name=serviceCtx,proto3" json:"serviceCtx,omitempty"`
	Ip         string      `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	BatchID    string      `protobuf:"bytes,6,opt,name=batchID,proto3" json:"batchID,omitempty"`
	FormID     string      `protobuf:"bytes,7,opt,name=formID,proto3" json:"formID,omitempty"`
	FileInfos  []*FileInfo `protobuf:"bytes,8,rep,name=fileInfos,proto3" json:"fileInfos,omitempty"`
}

func (x *FileSaveDataRequest) Reset() {
	*x = FileSaveDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_client_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileSaveDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSaveDataRequest) ProtoMessage() {}

func (x *FileSaveDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_client_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSaveDataRequest.ProtoReflect.Descriptor instead.
func (*FileSaveDataRequest) Descriptor() ([]byte, []int) {
	return file_file_client_proto_rawDescGZIP(), []int{3}
}

func (x *FileSaveDataRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *FileSaveDataRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *FileSaveDataRequest) GetServiceCtx() string {
	if x != nil {
		return x.ServiceCtx
	}
	return ""
}

func (x *FileSaveDataRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *FileSaveDataRequest) GetBatchID() string {
	if x != nil {
		return x.BatchID
	}
	return ""
}

func (x *FileSaveDataRequest) GetFormID() string {
	if x != nil {
		return x.FormID
	}
	return ""
}

func (x *FileSaveDataRequest) GetFileInfos() []*FileInfo {
	if x != nil {
		return x.FileInfos
	}
	return nil
}

type FileSaveDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output []byte `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *FileSaveDataResponse) Reset() {
	*x = FileSaveDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_client_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileSaveDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSaveDataResponse) ProtoMessage() {}

func (x *FileSaveDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_client_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSaveDataResponse.ProtoReflect.Descriptor instead.
func (*FileSaveDataResponse) Descriptor() ([]byte, []int) {
	return file_file_client_proto_rawDescGZIP(), []int{4}
}

func (x *FileSaveDataResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_file_client_proto protoreflect.FileDescriptor

var file_file_client_proto_rawDesc = []byte{
	0x0a, 0x11, 0x66, 0x69, 0x6c, 0x65, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22,
	0x60, 0x0a, 0x10, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x6f,
	0x72, 0x67, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49,
	0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x74, 0x78, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x74,
	0x78, 0x22, 0xa9, 0x01, 0x0a, 0x11, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x33, 0x44, 0x69, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x33, 0x44, 0x69, 0x72, 0x12, 0x20, 0x0a,
	0x0b, 0x6d, 0x61, 0x78, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x2a, 0x0a, 0x10, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x13, 0x61,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x13, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0xcc, 0x01,
	0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2a, 0x0a, 0x10, 0x6f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x46, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x33, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x33, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x66, 0x6f, 0x72, 0x6d, 0x4b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x66, 0x6f, 0x72, 0x6d, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x49, 0x44,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x49, 0x44, 0x22, 0xd9, 0x01, 0x0a,
	0x13, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x61, 0x76, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x6f, 0x72, 0x67, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x67,
	0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x74, 0x78,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43,
	0x74, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x74, 0x63, 0x68, 0x49, 0x44, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x74, 0x63, 0x68, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x6f, 0x72, 0x6d, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f,
	0x72, 0x6d, 0x49, 0x44, 0x12, 0x32, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x66,
	0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x2e, 0x0a, 0x14, 0x46, 0x69, 0x6c, 0x65,
	0x53, 0x61, 0x76, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x32, 0xac, 0x01, 0x0a, 0x0a, 0x46, 0x69, 0x6c,
	0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x4b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1c, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0c, 0x53, 0x61, 0x76, 0x65, 0x46, 0x69, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x61, 0x76, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x61, 0x76, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6f, 0x6c, 0x79, 0x2d, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x2f, 0x6d, 0x6f, 0x6c, 0x79, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_file_client_proto_rawDescOnce sync.Once
	file_file_client_proto_rawDescData = file_file_client_proto_rawDesc
)

func file_file_client_proto_rawDescGZIP() []byte {
	file_file_client_proto_rawDescOnce.Do(func() {
		file_file_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_file_client_proto_rawDescData)
	})
	return file_file_client_proto_rawDescData
}

var file_file_client_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_file_client_proto_goTypes = []interface{}{
	(*FileRulesRequest)(nil),     // 0: fileclient.FileRulesRequest
	(*FileRulesResponse)(nil),    // 1: fileclient.FileRulesResponse
	(*FileInfo)(nil),             // 2: fileclient.FileInfo
	(*FileSaveDataRequest)(nil),  // 3: fileclient.FileSaveDataRequest
	(*FileSaveDataResponse)(nil), // 4: fileclient.FileSaveDataResponse
}
var file_file_client_proto_depIdxs = []int32{
	2, // 0: fileclient.FileSaveDataRequest.fileInfos:type_name -> fileclient.FileInfo
	0, // 1: fileclient.FileClient.GetFileRules:input_type -> fileclient.FileRulesRequest
	3, // 2: fileclient.FileClient.SaveFileData:input_type -> fileclient.FileSaveDataRequest
	1, // 3: fileclient.FileClient.GetFileRules:output_type -> fileclient.FileRulesResponse
	4, // 4: fileclient.FileClient.SaveFileData:output_type -> fileclient.FileSaveDataResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_file_client_proto_init() }
func file_file_client_proto_init() {
	if File_file_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_file_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileRulesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileRulesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_client_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileSaveDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_client_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileSaveDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_file_client_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_client_proto_goTypes,
		DependencyIndexes: file_file_client_proto_depIdxs,
		MessageInfos:      file_file_client_proto_msgTypes,
	}.Build()
	File_file_client_proto = out.File
	file_file_client_proto_rawDesc = nil
	file_file_client_proto_goTypes = nil
	file_file_client_proto_depIdxs = nil
}
