// This is the command used to generate the Go code from this proto file.
// protoc -Ipb --go_out=./pb --go_opt=module=github.com/moly-space/molylibs/pb --go-grpc_out=./pb --go-grpc_opt=module=github.com/moly-space/molylibs/pb pb/hook-service.proto

// The syntax for this file is proto3.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: hook-service.proto

// The package for this file is hookservice.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HooksRequest is the request message for getting a list of hooks.
// The service field represents the service (like broker-service) for which to get the hooks.
type HookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"` // The service for which to get the hooks.
}

func (x *HookRequest) Reset() {
	*x = HookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hook_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookRequest) ProtoMessage() {}

func (x *HookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hook_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookRequest.ProtoReflect.Descriptor instead.
func (*HookRequest) Descriptor() ([]byte, []int) {
	return file_hook_service_proto_rawDescGZIP(), []int{0}
}

func (x *HookRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// Hook is the message representing a hook.
type Hook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID           string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`                     // The ID of the hook.
	Tag          string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`                   // The method (like GET, POST) of the hook.
	Priority     int32  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`        // The priority of the hook.
	CallbackType string `protobuf:"bytes,4,opt,name=callbackType,proto3" json:"callbackType,omitempty"` // The type of the callback for the hook.
	CallbackAddr string `protobuf:"bytes,5,opt,name=callbackAddr,proto3" json:"callbackAddr,omitempty"` // The address of the callback for the hook.
	CallbackFunc string `protobuf:"bytes,6,opt,name=callbackFunc,proto3" json:"callbackFunc,omitempty"` // The type of the callback for the hook. This seems to be a duplicate and might be an error.
}

func (x *Hook) Reset() {
	*x = Hook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hook_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hook) ProtoMessage() {}

func (x *Hook) ProtoReflect() protoreflect.Message {
	mi := &file_hook_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hook.ProtoReflect.Descriptor instead.
func (*Hook) Descriptor() ([]byte, []int) {
	return file_hook_service_proto_rawDescGZIP(), []int{1}
}

func (x *Hook) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Hook) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Hook) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Hook) GetCallbackType() string {
	if x != nil {
		return x.CallbackType
	}
	return ""
}

func (x *Hook) GetCallbackAddr() string {
	if x != nil {
		return x.CallbackAddr
	}
	return ""
}

func (x *Hook) GetCallbackFunc() string {
	if x != nil {
		return x.CallbackFunc
	}
	return ""
}

type RunHookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallbackFunc string `protobuf:"bytes,1,opt,name=callbackFunc,proto3" json:"callbackFunc,omitempty"` // The callback function to call after the hook is run.
	Xhost        string `protobuf:"bytes,2,opt,name=xhost,proto3" json:"xhost,omitempty"`               // The X-Host to use for the hook.
	JwtClaims    []byte `protobuf:"bytes,3,opt,name=jwtClaims,proto3" json:"jwtClaims,omitempty"`       // The JWT to use for the hook.
	Data         []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                 // The data to send to the hook.
}

func (x *RunHookRequest) Reset() {
	*x = RunHookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hook_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunHookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunHookRequest) ProtoMessage() {}

func (x *RunHookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hook_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunHookRequest.ProtoReflect.Descriptor instead.
func (*RunHookRequest) Descriptor() ([]byte, []int) {
	return file_hook_service_proto_rawDescGZIP(), []int{2}
}

func (x *RunHookRequest) GetCallbackFunc() string {
	if x != nil {
		return x.CallbackFunc
	}
	return ""
}

func (x *RunHookRequest) GetXhost() string {
	if x != nil {
		return x.Xhost
	}
	return ""
}

func (x *RunHookRequest) GetJwtClaims() []byte {
	if x != nil {
		return x.JwtClaims
	}
	return nil
}

func (x *RunHookRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RunHookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`    // The data returned by the hook.
	Error bool   `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"` // Whether the hook was successful.
}

func (x *RunHookResponse) Reset() {
	*x = RunHookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hook_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunHookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunHookResponse) ProtoMessage() {}

func (x *RunHookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hook_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunHookResponse.ProtoReflect.Descriptor instead.
func (*RunHookResponse) Descriptor() ([]byte, []int) {
	return file_hook_service_proto_rawDescGZIP(), []int{3}
}

func (x *RunHookResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RunHookResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

// HookListResponse is the response message for getting a list of hooks.
// It contains a list of Hook messages.
type HookListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hooks []*Hook `protobuf:"bytes,1,rep,name=hooks,proto3" json:"hooks,omitempty"` // The list of hooks.
}

func (x *HookListResponse) Reset() {
	*x = HookListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hook_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HookListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookListResponse) ProtoMessage() {}

func (x *HookListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hook_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookListResponse.ProtoReflect.Descriptor instead.
func (*HookListResponse) Descriptor() ([]byte, []int) {
	return file_hook_service_proto_rawDescGZIP(), []int{4}
}

func (x *HookListResponse) GetHooks() []*Hook {
	if x != nil {
		return x.Hooks
	}
	return nil
}

var File_hook_service_proto protoreflect.FileDescriptor

var file_hook_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x68, 0x6f, 0x6f, 0x6b, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x68, 0x6f, 0x6f, 0x6b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x22, 0x27, 0x0a, 0x0b, 0x48, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0xb0, 0x01, 0x0a, 0x04, 0x48,
	0x6f, 0x6f, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x41, 0x64, 0x64, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x46, 0x75, 0x6e, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x46, 0x75, 0x6e, 0x63, 0x22, 0x7c, 0x0a,
	0x0e, 0x52, 0x75, 0x6e, 0x48, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x22, 0x0a, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x46, 0x75, 0x6e, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x46,
	0x75, 0x6e, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x78, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x78, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6a, 0x77, 0x74,
	0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6a, 0x77,
	0x74, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3b, 0x0a, 0x0f, 0x52,
	0x75, 0x6e, 0x48, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3b, 0x0a, 0x10, 0x48, 0x6f, 0x6f, 0x6b,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x05,
	0x68, 0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x6f,
	0x6f, 0x6b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x48, 0x6f, 0x6f, 0x6b, 0x52, 0x05,
	0x68, 0x6f, 0x6f, 0x6b, 0x73, 0x32, 0x98, 0x01, 0x0a, 0x0b, 0x48, 0x6f, 0x6f, 0x6b, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x6f, 0x6b,
	0x73, 0x12, 0x18, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x48, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x68, 0x6f,
	0x6f, 0x6b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x48, 0x6f, 0x6f, 0x6b, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x07, 0x52, 0x75,
	0x6e, 0x48, 0x6f, 0x6f, 0x6b, 0x12, 0x1b, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x52, 0x75, 0x6e, 0x48, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x68, 0x6f, 0x6f, 0x6b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x52, 0x75, 0x6e, 0x48, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x6f, 0x6c, 0x79, 0x2d, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2f, 0x6d, 0x6f, 0x6c, 0x79, 0x6c, 0x69,
	0x62, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hook_service_proto_rawDescOnce sync.Once
	file_hook_service_proto_rawDescData = file_hook_service_proto_rawDesc
)

func file_hook_service_proto_rawDescGZIP() []byte {
	file_hook_service_proto_rawDescOnce.Do(func() {
		file_hook_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_hook_service_proto_rawDescData)
	})
	return file_hook_service_proto_rawDescData
}

var file_hook_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_hook_service_proto_goTypes = []interface{}{
	(*HookRequest)(nil),      // 0: hookservice.HookRequest
	(*Hook)(nil),             // 1: hookservice.Hook
	(*RunHookRequest)(nil),   // 2: hookservice.RunHookRequest
	(*RunHookResponse)(nil),  // 3: hookservice.RunHookResponse
	(*HookListResponse)(nil), // 4: hookservice.HookListResponse
}
var file_hook_service_proto_depIdxs = []int32{
	1, // 0: hookservice.HookListResponse.hooks:type_name -> hookservice.Hook
	0, // 1: hookservice.HookService.GetHooks:input_type -> hookservice.HookRequest
	2, // 2: hookservice.HookService.RunHook:input_type -> hookservice.RunHookRequest
	4, // 3: hookservice.HookService.GetHooks:output_type -> hookservice.HookListResponse
	3, // 4: hookservice.HookService.RunHook:output_type -> hookservice.RunHookResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hook_service_proto_init() }
func file_hook_service_proto_init() {
	if File_hook_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hook_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hook_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hook_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunHookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hook_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunHookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hook_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HookListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hook_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hook_service_proto_goTypes,
		DependencyIndexes: file_hook_service_proto_depIdxs,
		MessageInfos:      file_hook_service_proto_msgTypes,
	}.Build()
	File_hook_service_proto = out.File
	file_hook_service_proto_rawDesc = nil
	file_hook_service_proto_goTypes = nil
	file_hook_service_proto_depIdxs = nil
}
