// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: hook-service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HookServiceClient is the client API for HookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HookServiceClient interface {
	// GetHooks is the RPC method for getting a list of hooks.
	// It takes a HooksRequest and returns a HookListResponse.
	GetHooks(ctx context.Context, in *HookRequest, opts ...grpc.CallOption) (*HookListResponse, error)
	RunHook(ctx context.Context, in *RunHookRequest, opts ...grpc.CallOption) (*RunHookResponse, error)
}

type hookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHookServiceClient(cc grpc.ClientConnInterface) HookServiceClient {
	return &hookServiceClient{cc}
}

func (c *hookServiceClient) GetHooks(ctx context.Context, in *HookRequest, opts ...grpc.CallOption) (*HookListResponse, error) {
	out := new(HookListResponse)
	err := c.cc.Invoke(ctx, "/hookservice.HookService/GetHooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hookServiceClient) RunHook(ctx context.Context, in *RunHookRequest, opts ...grpc.CallOption) (*RunHookResponse, error) {
	out := new(RunHookResponse)
	err := c.cc.Invoke(ctx, "/hookservice.HookService/RunHook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HookServiceServer is the server API for HookService service.
// All implementations must embed UnimplementedHookServiceServer
// for forward compatibility
type HookServiceServer interface {
	// GetHooks is the RPC method for getting a list of hooks.
	// It takes a HooksRequest and returns a HookListResponse.
	GetHooks(context.Context, *HookRequest) (*HookListResponse, error)
	RunHook(context.Context, *RunHookRequest) (*RunHookResponse, error)
	mustEmbedUnimplementedHookServiceServer()
}

// UnimplementedHookServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHookServiceServer struct {
}

func (UnimplementedHookServiceServer) GetHooks(context.Context, *HookRequest) (*HookListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHooks not implemented")
}
func (UnimplementedHookServiceServer) RunHook(context.Context, *RunHookRequest) (*RunHookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunHook not implemented")
}
func (UnimplementedHookServiceServer) mustEmbedUnimplementedHookServiceServer() {}

// UnsafeHookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HookServiceServer will
// result in compilation errors.
type UnsafeHookServiceServer interface {
	mustEmbedUnimplementedHookServiceServer()
}

func RegisterHookServiceServer(s grpc.ServiceRegistrar, srv HookServiceServer) {
	s.RegisterService(&HookService_ServiceDesc, srv)
}

func _HookService_GetHooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HookServiceServer).GetHooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hookservice.HookService/GetHooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HookServiceServer).GetHooks(ctx, req.(*HookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HookService_RunHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HookServiceServer).RunHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hookservice.HookService/RunHook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HookServiceServer).RunHook(ctx, req.(*RunHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HookService_ServiceDesc is the grpc.ServiceDesc for HookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hookservice.HookService",
	HandlerType: (*HookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHooks",
			Handler:    _HookService_GetHooks_Handler,
		},
		{
			MethodName: "RunHook",
			Handler:    _HookService_RunHook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hook-service.proto",
}
