//protoc -Ipb --go_out=./pb --go_opt=module=github.com/moly-space/molylibs/pb --go-grpc_out=./pb --go-grpc_opt=module=github.com/moly-space/molylibs/pb pb/organization-service.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: organization-service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *OrgRequest) Reset() {
	*x = OrgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_organization_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgRequest) ProtoMessage() {}

func (x *OrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgRequest.ProtoReflect.Descriptor instead.
func (*OrgRequest) Descriptor() ([]byte, []int) {
	return file_organization_service_proto_rawDescGZIP(), []int{0}
}

func (x *OrgRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type OrgSettingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host  string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	OrgID string `protobuf:"bytes,2,opt,name=orgID,proto3" json:"orgID,omitempty"`
	Key   string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *OrgSettingRequest) Reset() {
	*x = OrgSettingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_organization_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgSettingRequest) ProtoMessage() {}

func (x *OrgSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgSettingRequest.ProtoReflect.Descriptor instead.
func (*OrgSettingRequest) Descriptor() ([]byte, []int) {
	return file_organization_service_proto_rawDescGZIP(), []int{1}
}

func (x *OrgSettingRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *OrgSettingRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *OrgSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type OrgIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *OrgIDResponse) Reset() {
	*x = OrgIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_organization_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgIDResponse) ProtoMessage() {}

func (x *OrgIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgIDResponse.ProtoReflect.Descriptor instead.
func (*OrgIDResponse) Descriptor() ([]byte, []int) {
	return file_organization_service_proto_rawDescGZIP(), []int{2}
}

func (x *OrgIDResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type OrgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Settings []byte `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	Info     []byte `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *OrgResponse) Reset() {
	*x = OrgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_organization_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgResponse) ProtoMessage() {}

func (x *OrgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgResponse.ProtoReflect.Descriptor instead.
func (*OrgResponse) Descriptor() ([]byte, []int) {
	return file_organization_service_proto_rawDescGZIP(), []int{3}
}

func (x *OrgResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *OrgResponse) GetSettings() []byte {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *OrgResponse) GetInfo() []byte {
	if x != nil {
		return x.Info
	}
	return nil
}

type OrgServiceSetting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value     string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ValueType string `protobuf:"bytes,3,opt,name=valueType,proto3" json:"valueType,omitempty"`
}

func (x *OrgServiceSetting) Reset() {
	*x = OrgServiceSetting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_organization_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgServiceSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgServiceSetting) ProtoMessage() {}

func (x *OrgServiceSetting) ProtoReflect() protoreflect.Message {
	mi := &file_organization_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgServiceSetting.ProtoReflect.Descriptor instead.
func (*OrgServiceSetting) Descriptor() ([]byte, []int) {
	return file_organization_service_proto_rawDescGZIP(), []int{4}
}

func (x *OrgServiceSetting) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OrgServiceSetting) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *OrgServiceSetting) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

type OrgServiceSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgID    string               `protobuf:"bytes,1,opt,name=orgID,proto3" json:"orgID,omitempty"`
	Service  string               `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Key      string               `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"` // slug or unit
	Settings []*OrgServiceSetting `protobuf:"bytes,4,rep,name=settings,proto3" json:"settings,omitempty"`
}

func (x *OrgServiceSettings) Reset() {
	*x = OrgServiceSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_organization_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgServiceSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgServiceSettings) ProtoMessage() {}

func (x *OrgServiceSettings) ProtoReflect() protoreflect.Message {
	mi := &file_organization_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgServiceSettings.ProtoReflect.Descriptor instead.
func (*OrgServiceSettings) Descriptor() ([]byte, []int) {
	return file_organization_service_proto_rawDescGZIP(), []int{5}
}

func (x *OrgServiceSettings) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *OrgServiceSettings) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *OrgServiceSettings) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OrgServiceSettings) GetSettings() []*OrgServiceSetting {
	if x != nil {
		return x.Settings
	}
	return nil
}

var File_organization_service_proto protoreflect.FileDescriptor

var file_organization_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6f, 0x72,
	0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x22, 0x20, 0x0a, 0x0a, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x22, 0x4f, 0x0a, 0x11, 0x4f, 0x72, 0x67, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x6f, 0x72, 0x67, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x67,
	0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0x1f, 0x0a, 0x0d, 0x4f, 0x72, 0x67, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x4d, 0x0a, 0x0b, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x22, 0x59, 0x0a, 0x11, 0x4f, 0x72, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x9a, 0x01, 0x0a, 0x12, 0x4f, 0x72, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x42, 0x0a, 0x08, 0x73, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6f, 0x72, 0x67,
	0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x4f, 0x72, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x32, 0xea, 0x03, 0x0a,
	0x13, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x49, 0x44,
	0x12, 0x1f, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f, 0x72, 0x67, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x12,
	0x1f, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x5a, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x12, 0x26, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f, 0x72, 0x67, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x69,
	0x0a, 0x15, 0x53, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x27, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f, 0x72,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x1a, 0x27, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f, 0x72, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x6e, 0x0a, 0x1a, 0x47, 0x65, 0x74,
	0x4f, 0x72, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x42, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x27, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f, 0x72,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x1a, 0x27, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f, 0x72, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6f, 0x6c, 0x79, 0x2d, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x2f, 0x6d, 0x6f, 0x6c, 0x79, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_organization_service_proto_rawDescOnce sync.Once
	file_organization_service_proto_rawDescData = file_organization_service_proto_rawDesc
)

func file_organization_service_proto_rawDescGZIP() []byte {
	file_organization_service_proto_rawDescOnce.Do(func() {
		file_organization_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_organization_service_proto_rawDescData)
	})
	return file_organization_service_proto_rawDescData
}

var file_organization_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_organization_service_proto_goTypes = []interface{}{
	(*OrgRequest)(nil),         // 0: organizationservice.OrgRequest
	(*OrgSettingRequest)(nil),  // 1: organizationservice.OrgSettingRequest
	(*OrgIDResponse)(nil),      // 2: organizationservice.OrgIDResponse
	(*OrgResponse)(nil),        // 3: organizationservice.OrgResponse
	(*OrgServiceSetting)(nil),  // 4: organizationservice.OrgServiceSetting
	(*OrgServiceSettings)(nil), // 5: organizationservice.OrgServiceSettings
}
var file_organization_service_proto_depIdxs = []int32{
	4, // 0: organizationservice.OrgServiceSettings.settings:type_name -> organizationservice.OrgServiceSetting
	0, // 1: organizationservice.OrganizationService.GetOrgID:input_type -> organizationservice.OrgRequest
	0, // 2: organizationservice.OrganizationService.GetOrg:input_type -> organizationservice.OrgRequest
	1, // 3: organizationservice.OrganizationService.GetOrgSettings:input_type -> organizationservice.OrgSettingRequest
	5, // 4: organizationservice.OrganizationService.SetOrgServiceSettings:input_type -> organizationservice.OrgServiceSettings
	5, // 5: organizationservice.OrganizationService.GetOrgServiceSettingsByKey:input_type -> organizationservice.OrgServiceSettings
	2, // 6: organizationservice.OrganizationService.GetOrgID:output_type -> organizationservice.OrgIDResponse
	3, // 7: organizationservice.OrganizationService.GetOrg:output_type -> organizationservice.OrgResponse
	3, // 8: organizationservice.OrganizationService.GetOrgSettings:output_type -> organizationservice.OrgResponse
	5, // 9: organizationservice.OrganizationService.SetOrgServiceSettings:output_type -> organizationservice.OrgServiceSettings
	5, // 10: organizationservice.OrganizationService.GetOrgServiceSettingsByKey:output_type -> organizationservice.OrgServiceSettings
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_organization_service_proto_init() }
func file_organization_service_proto_init() {
	if File_organization_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_organization_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_organization_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrgSettingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_organization_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrgIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_organization_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_organization_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrgServiceSetting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_organization_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrgServiceSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_organization_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_organization_service_proto_goTypes,
		DependencyIndexes: file_organization_service_proto_depIdxs,
		MessageInfos:      file_organization_service_proto_msgTypes,
	}.Build()
	File_organization_service_proto = out.File
	file_organization_service_proto_rawDesc = nil
	file_organization_service_proto_goTypes = nil
	file_organization_service_proto_depIdxs = nil
}
