//protoc -Ipb --go_out=./pb --go_opt=module=github.com/moly-space/molylibs/pb --go-grpc_out=./pb --go-grpc_opt=module=github.com/moly-space/molylibs/pb pb/rbac-service.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: rbac-service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RBACRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host      string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Service   string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	ModelCtx  string `protobuf:"bytes,3,opt,name=modelCtx,proto3" json:"modelCtx,omitempty"`
	PolicyCtx string `protobuf:"bytes,4,opt,name=policyCtx,proto3" json:"policyCtx,omitempty"`
}

func (x *RBACRequest) Reset() {
	*x = RBACRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RBACRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RBACRequest) ProtoMessage() {}

func (x *RBACRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RBACRequest.ProtoReflect.Descriptor instead.
func (*RBACRequest) Descriptor() ([]byte, []int) {
	return file_rbac_service_proto_rawDescGZIP(), []int{0}
}

func (x *RBACRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RBACRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *RBACRequest) GetModelCtx() string {
	if x != nil {
		return x.ModelCtx
	}
	return ""
}

func (x *RBACRequest) GetPolicyCtx() string {
	if x != nil {
		return x.PolicyCtx
	}
	return ""
}

type RBACResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Policy []string `protobuf:"bytes,1,rep,name=policy,proto3" json:"policy,omitempty"`
}

func (x *RBACResponse) Reset() {
	*x = RBACResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RBACResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RBACResponse) ProtoMessage() {}

func (x *RBACResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RBACResponse.ProtoReflect.Descriptor instead.
func (*RBACResponse) Descriptor() ([]byte, []int) {
	return file_rbac_service_proto_rawDescGZIP(), []int{1}
}

func (x *RBACResponse) GetPolicy() []string {
	if x != nil {
		return x.Policy
	}
	return nil
}

type ModelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *ModelResponse) Reset() {
	*x = ModelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelResponse) ProtoMessage() {}

func (x *ModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelResponse.ProtoReflect.Descriptor instead.
func (*ModelResponse) Descriptor() ([]byte, []int) {
	return file_rbac_service_proto_rawDescGZIP(), []int{2}
}

func (x *ModelResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ModelAndPolicyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model  string   `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Policy []string `protobuf:"bytes,2,rep,name=policy,proto3" json:"policy,omitempty"`
}

func (x *ModelAndPolicyResponse) Reset() {
	*x = ModelAndPolicyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelAndPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelAndPolicyResponse) ProtoMessage() {}

func (x *ModelAndPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelAndPolicyResponse.ProtoReflect.Descriptor instead.
func (*ModelAndPolicyResponse) Descriptor() ([]byte, []int) {
	return file_rbac_service_proto_rawDescGZIP(), []int{3}
}

func (x *ModelAndPolicyResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ModelAndPolicyResponse) GetPolicy() []string {
	if x != nil {
		return x.Policy
	}
	return nil
}

var File_rbac_service_proto protoreflect.FileDescriptor

var file_rbac_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x62, 0x61, 0x63, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x62, 0x61, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x22, 0x75, 0x0a, 0x0b, 0x52, 0x42, 0x41, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x6f, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x74, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x74, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x43, 0x74, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x74, 0x78, 0x22, 0x26, 0x0a, 0x0c, 0x52, 0x42, 0x41, 0x43,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x22, 0x25, 0x0a, 0x0d, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x46, 0x0a, 0x16, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x41, 0x6e, 0x64, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x32,
	0xe5, 0x01, 0x0a, 0x0b, 0x52, 0x42, 0x41, 0x43, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x40, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x18, 0x2e, 0x72,
	0x62, 0x61, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x42, 0x41, 0x43, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x42, 0x41, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x40, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x18, 0x2e,
	0x72, 0x62, 0x61, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x42, 0x41, 0x43,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x41,
	0x6e, 0x64, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x18, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x42, 0x41, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x41, 0x6e, 0x64, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6f, 0x6c, 0x79, 0x2d, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x2f, 0x6d, 0x6f, 0x6c, 0x79, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rbac_service_proto_rawDescOnce sync.Once
	file_rbac_service_proto_rawDescData = file_rbac_service_proto_rawDesc
)

func file_rbac_service_proto_rawDescGZIP() []byte {
	file_rbac_service_proto_rawDescOnce.Do(func() {
		file_rbac_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_rbac_service_proto_rawDescData)
	})
	return file_rbac_service_proto_rawDescData
}

var file_rbac_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rbac_service_proto_goTypes = []interface{}{
	(*RBACRequest)(nil),            // 0: rbacservice.RBACRequest
	(*RBACResponse)(nil),           // 1: rbacservice.RBACResponse
	(*ModelResponse)(nil),          // 2: rbacservice.ModelResponse
	(*ModelAndPolicyResponse)(nil), // 3: rbacservice.ModelAndPolicyResponse
}
var file_rbac_service_proto_depIdxs = []int32{
	0, // 0: rbacservice.RBACService.GetPolicy:input_type -> rbacservice.RBACRequest
	0, // 1: rbacservice.RBACService.GetModel:input_type -> rbacservice.RBACRequest
	0, // 2: rbacservice.RBACService.GetModelAndPolicy:input_type -> rbacservice.RBACRequest
	1, // 3: rbacservice.RBACService.GetPolicy:output_type -> rbacservice.RBACResponse
	2, // 4: rbacservice.RBACService.GetModel:output_type -> rbacservice.ModelResponse
	3, // 5: rbacservice.RBACService.GetModelAndPolicy:output_type -> rbacservice.ModelAndPolicyResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rbac_service_proto_init() }
func file_rbac_service_proto_init() {
	if File_rbac_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rbac_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RBACRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rbac_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RBACResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rbac_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rbac_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelAndPolicyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rbac_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rbac_service_proto_goTypes,
		DependencyIndexes: file_rbac_service_proto_depIdxs,
		MessageInfos:      file_rbac_service_proto_msgTypes,
	}.Build()
	File_rbac_service_proto = out.File
	file_rbac_service_proto_rawDesc = nil
	file_rbac_service_proto_goTypes = nil
	file_rbac_service_proto_depIdxs = nil
}
